const mockStudents = [
    { studentID: 100, studentFirstName: 'John', studentLastName: 'Doe', studentEmail: 'john.doe@aggies.ncat.edu', studentPassword: 'password', studentStatus: 'Full-Time', studentClassification: 'Sophomore', studentGPA: 3.5, advisorID: 170, studentMajor: 'Computer Science', studentCredit: 120 },
    { studentID: 101, studentFirstName: 'Jane', studentLastName: 'Dole', studentEmail: 'jd@aggies.ncat.edu', studentPassword: 'password', studentStatus: 'Full-Time', studentClassification: 'Junior', studentGPA: 3.2, advisorID: 170, studentMajor: 'Computer Science', studentCredit: 100 },
    { studentID: 107, studentFirstName: 'Linda', studentLastName: 'Payne', studentEmail: 'lp@aggies.ncat.edu', studentPassword: 'password', studentStatus: 'Full-Time', studentClassification: 'Sophomore', studentGPA: 3.7, advisorID: 172, studentMajor: 'Computer Science', studentCredit: 120 },
    { studentID: 108, studentFirstName: 'John', studentLastName: 'Cena', studentEmail: 'jc@aggies.ncat.edu', studentPassword: 'password', studentStatus: 'Full-Time', studentClassification: 'Junior', studentGPA: 3.0, advisorID: 172, studentMajor: 'Computer Science', studentCredit: 110 },
    { studentID: 105, studentFirstName: 'Michael', studentLastName: 'Jackson', studentEmail: 'mk@aggies.ncat.edu', studentPassword: 'password', studentStatus: 'Full-Time', studentClassification: 'Sophomore', studentGPA: 3.6, advisorID: 174, studentMajor: 'Computer Science', studentCredit: 119 },
    { studentID: 106, studentFirstName: 'Jane', studentLastName: 'Dole', studentEmail: 'jdl@aggies.ncat.edu', studentPassword: 'password', studentStatus: 'Full-Time', studentClassification: 'Junior', studentGPA: 3.3, advisorID: 174, studentMajor: 'Computer Science', studentCredit: 119 },
    { studentID: 109, studentFirstName: 'Missy', studentLastName: 'Hampton', studentEmail: 'mh@aggies.ncat.edu', studentPassword: 'password', studentStatus: 'Full-Time', studentClassification: 'Sophomore', studentGPA: 3.5, advisorID: 178, studentMajor: 'Computer Science', studentCredit: 120 },
    { studentID: 110, studentFirstName: 'Jillian', studentLastName: 'Kane', studentEmail: 'jk@aggies.ncat.edu', studentPassword: 'password', studentStatus: 'Full-Time', studentClassification: 'Junior', studentGPA: 3.2, advisorID: 178, studentMajor: 'Computer Science', studentCredit: 107 },
    { studentID: 120, studentFirstName: 'John', studentLastName: 'Grande', studentEmail: 'jg@aggies.ncat.edu', studentPassword: 'password', studentStatus: 'Full-Time', studentClassification: 'Sophomore', studentGPA: 3.5, advisorID: 176, studentMajor: 'Computer Science', studentCredit: 121 },
    { studentID: 122, studentFirstName: 'Joseph', studentLastName: 'Hall', studentEmail: 'jh@aggies.ncat.edu', studentPassword: 'password', studentStatus: 'Full-Time', studentClassification: 'Junior', studentGPA: 3.2, advisorID: 176, studentMajor: 'Computer Science', studentCredit: 102 },
];